In [55]:
from numpy import *;

In [57]:
mat1=array([[1,2,3],[5,6,7]])
print(mat1)

[[1 2 3]
 [5 6 7]]


In [83]:
print(mat1[0,1])

2


In [ ]:
mat1[1,2]=88
print(mat1[1,2])

In [61]:
print(mat1.dtype)

int32


In [63]:
print(mat1.ndim)

2


In [65]:
print(mat1.size)

6


In [67]:
print(mat1.shape)

(2, 3)


In [125]:
print(f"mean of array {mat1.mean()}")

mean of array 17.5


In [101]:
print(f"mean of rows{mat1.mean(axis=0)}")

mean of rows[ 3.   4.  45.5]


In [103]:
print(f"mean of columns{mat1.mean(axis=1)}")

mean of columns[ 2. 33.]


In [129]:
print(f"sum of array elements {mat1.sum()}")

sum of array elements 105


In [115]:
print(f"sum of columns{mat1.sum(axis=1)}")

msum of columns[ 6 99]


In [105]:
print(f"sum of rows{mat1.sum(axis=0)}")

msum of rows[ 6  8 91]


In [133]:
print(f"maximum element ofarray {mat1.max()}")

maximum element ofarray 88


In [117]:
print(f"maximum element ofcolumns{mat1.max(axis=1)}")

maximum element ofcolumns[ 3 88]


In [121]:
print(f"maximum element of rows{mat1.max(axis=0)}")

maximum element of rows[ 5  6 88]


In [135]:
print(f"miniimum element ofarray {mat1.min()}")

miniimum element ofarray 1


In [111]:
print(f"minimum element of rows{mat1.min(axis=0)}")

minimum element of rows[1 2 3]


In [ ]:
print(f"maximum element of rows{mat1.max(axis=1)}")

In [71]:
print(mat3.shape)
print(mat3.ndim)

(3, 2)
2


In [75]:
arr=mat1.flatten()
print(arr)

[1 2 3 5 6 7]


In [ ]:
mat3 = mat1.reshape(3,2)
print(mat3)